services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: financial-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: financial-frontend
    depends_on:
      - backend
