"""increase numeric precision to 20

Revision ID: 663072e2aad6
Revises: f475ef2e33e9
Create Date: 2025-10-29 00:41:05.263063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663072e2aad6'
down_revision: Union[str, Sequence[str], None] = 'f475ef2e33e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adjusted_cost_basis_sells', 'shares',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('adjusted_cost_basis_sells', 'transaction_amount',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('adjusted_cost_basis_sells', 'profit',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('adjusted_cost_basis_sells', 'proceeds',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('adjusted_cost_basis_sells', 'adjusted_cost',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adjusted_cost_basis_sells', 'adjusted_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=12, scale=8),
               existing_nullable=False)
    op.alter_column('adjusted_cost_basis_sells', 'proceeds',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=12, scale=8),
               existing_nullable=False)
    op.alter_column('adjusted_cost_basis_sells', 'profit',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=12, scale=8),
               existing_nullable=False)
    op.alter_column('adjusted_cost_basis_sells', 'transaction_amount',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=12, scale=8),
               existing_nullable=False)
    op.alter_column('adjusted_cost_basis_sells', 'shares',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.NUMERIC(precision=12, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###
