"""Initial migration with all models

Revision ID: ccdb6f518278
Revises: 
Create Date: 2025-10-07 23:46:56.518826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccdb6f518278'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_id'), 'financial_accounts', ['id'], unique=False)
    op.create_table('adjusted_cost_basis_sells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('profit', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('proceeds', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('adjusted_cost', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('financial_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjusted_cost_basis_sells_id'), 'adjusted_cost_basis_sells', ['id'], unique=False)
    op.create_index(op.f('ix_adjusted_cost_basis_sells_stock'), 'adjusted_cost_basis_sells', ['stock'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjusted_cost_basis_sells_stock'), table_name='adjusted_cost_basis_sells')
    op.drop_index(op.f('ix_adjusted_cost_basis_sells_id'), table_name='adjusted_cost_basis_sells')
    op.drop_table('adjusted_cost_basis_sells')
    op.drop_index(op.f('ix_financial_accounts_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
