"""Add refresh_tokens and cascade deletes for all models under User

Revision ID: f475ef2e33e9
Revises: ccdb6f518278
Create Date: 2025-10-13 23:36:26.117332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f475ef2e33e9'
down_revision: Union[str, Sequence[str], None] = 'ccdb6f518278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_refresh_token'), 'refresh_tokens', ['refresh_token'], unique=True)
    op.drop_constraint(op.f('adjusted_cost_basis_sells_financial_account_id_fkey'), 'adjusted_cost_basis_sells', type_='foreignkey')
    op.create_foreign_key(None, 'adjusted_cost_basis_sells', 'financial_accounts', ['financial_account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('financial_accounts_user_id_fkey'), 'financial_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'financial_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('financial_accounts_user_id_fkey'), 'financial_accounts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'adjusted_cost_basis_sells', type_='foreignkey')
    op.create_foreign_key(op.f('adjusted_cost_basis_sells_financial_account_id_fkey'), 'adjusted_cost_basis_sells', 'financial_accounts', ['financial_account_id'], ['id'])
    op.drop_index(op.f('ix_refresh_tokens_refresh_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
